export const SITE = {
  name: 'RO Service Now',
  tagline: 'Professional RO Water Purifier Repair & Service in Bangalore',
  description: 'Expert RO water purifier repair, installation, and maintenance services in Bangalore. Same day doorstep service, genuine spare parts, and certified technicians. Call 080502 91180.',
  phone: '080502 91180',
  phoneFormatted: '080502 91180',
  phoneRaw: '08050291180',
  email: 'customercaresupports22@gmail.com',
  address: {
    street: '',
    city: 'Bangalore',
    state: 'Karnataka',
    zip: '',
    country: 'India',
    full: 'Bangalore, Karnataka, India',
  },
  businessHours: {
    weekdays: '8:00 AM - 8:00 PM',
    saturday: '8:00 AM - 6:00 PM',
    sunday: '9:00 AM - 5:00 PM',
    support: '24/7',
  },
  social: {
    facebook: '#',
    instagram: '#',
    twitter: '#',
    youtube: '#',
  },
  url: 'https://roservicenow.in',
  googleRating: '4.8',
  reviewCount: '2500',
  customersCount: '10,000+',
};

export const NAV_LINKS = [
  { name: 'About Us', path: '/about', icon: 'Info' },
  {
    name: 'Services',
    path: '/services',
    icon: 'Wrench',
    children: [
      { name: 'RO Repair', path: '/services/ro-repair' },
      { name: 'RO Installation', path: '/services/ro-installation' },
      { name: 'AMC Plans', path: '/services/amc-plans' },
      { name: 'Filter Replacement', path: '/services/filter-replacement' },
      { name: 'All Services', path: '/services' },
    ],
  },
  {
    name: 'Brands',
    path: '/brands',
    icon: 'Award',
    children: [
      { name: 'Kent', path: '/brands/kent' },
      { name: 'Aquaguard', path: '/brands/aquaguard' },
      { name: 'Pureit', path: '/brands/pureit' },
      { name: 'AO Smith', path: '/brands/ao-smith' },
      { name: 'LG', path: '/brands/lg' },
    ],
  },
  { name: 'Contact Us', path: '/contact', icon: 'Phone' },
  { name: 'Privacy Policy', path: '/privacy-policy', icon: 'Shield' },
  { name: 'Terms of Service', path: '/terms', icon: 'FileText' },
  { name: 'Disclaimer', path: '/disclaimer', icon: 'Shield' },
];

export const SERVICES = [
  {
    id: 'ro-repair',
    title: 'RO Repair',
    shortTitle: 'RO Repair',
    description: 'Fast repair for all RO problems',
    icon: 'Wrench',
    color: 'primary',
  },
  {
    id: 'ro-installation',
    title: 'RO Installation',
    shortTitle: 'Installation',
    description: 'Professional installation at your home',
    icon: 'Settings',
    color: 'secondary',
  },
  {
    id: 'ro-uninstallation',
    title: 'RO Uninstallation',
    shortTitle: 'Uninstallation',
    description: 'Safe removal and relocation of your RO system',
    icon: 'Power',
    color: 'navy',
  },
  {
    id: 'filter-replacement',
    title: 'Filter Replacement',
    shortTitle: 'Filters',
    description: 'Genuine filters replacement',
    icon: 'Filter',
    color: 'primary',
  },
  {
    id: 'membrane-replacement',
    title: 'Membrane Replacement',
    shortTitle: 'Membrane',
    description: 'High quality membrane replacement',
    icon: 'CircleDot',
    color: 'secondary',
  },
  {
    id: 'amc-plans',
    title: 'AMC Plans',
    shortTitle: 'AMC',
    description: 'Annual maintenance plans available',
    icon: 'Calendar',
    color: 'primary',
  },
  {
    id: 'water-leakage-repair',
    title: 'Water Leakage Repair',
    shortTitle: 'Leakage',
    description: 'Fix water leakage quickly',
    icon: 'Droplets',
    color: 'danger',
  },
  {
    id: 'low-water-flow',
    title: 'Low Water Flow Repair',
    shortTitle: 'Low Flow',
    description: 'Improve RO water flow',
    icon: 'Gauge',
    color: 'warning',
  },
  {
    id: 'pump-repair',
    title: 'Pump Repair',
    shortTitle: 'Pump',
    description: 'RO pump repair & replacement',
    icon: 'Cog',
    color: 'primary',
  },
  {
    id: 'motor-repair',
    title: 'Motor Repair',
    shortTitle: 'Motor',
    description: 'Professional motor repair services',
    icon: 'Zap',
    color: 'secondary',
  },
  {
    id: 'tds-adjustment',
    title: 'TDS Adjustment',
    shortTitle: 'TDS',
    description: 'Adjust TDS level as per your need',
    icon: 'Activity',
    color: 'primary',
  },
  {
    id: 'periodic-maintenance',
    title: 'Periodic Maintenance',
    shortTitle: 'Maintenance',
    description: 'Keep your RO in best condition',
    icon: 'RefreshCw',
    color: 'secondary',
  },
];

export const BRANDS = [
  {
    id: 'kent',
    name: 'Kent',
    fullName: 'Kent RO Systems',
    tagline: 'Mineral RO Water Purifiers',
    description: 'Kent is one of India\'s leading water purifier brands, known for its advanced RO+UV+UF water purification technology. We provide complete Kent RO service in Bangalore.',
    color: '#1e40af',
    services: ['Kent RO Repair', 'Kent Filter Change', 'Kent Membrane Replacement', 'Kent AMC'],
  },
  {
    id: 'aquaguard',
    name: 'Aquaguard',
    fullName: 'Aquaguard (Eureka Forbes)',
    tagline: 'Paani Ka Doctor',
    description: 'Aquaguard is India\'s most trusted water purifier brand from Eureka Forbes, offering advanced multi-stage water purification. Expert Aquaguard service in Bangalore.',
    color: '#059669',
    services: ['Aquaguard Repair', 'Aquaguard Service', 'Aquaguard Filter Change', 'Aquaguard AMC'],
  },
  {
    id: 'pureit',
    name: 'Pureit',
    fullName: 'Pureit (HUL)',
    tagline: 'Pure Water for Every Home',
    description: 'Pureit from Hindustan Unilever provides advanced water purification technology at affordable prices. Professional Pureit service in Bangalore.',
    color: '#0369a1',
    services: ['Pureit Repair', 'Pureit Service', 'Pureit Filter Change', 'Pureit AMC'],
  },
  {
    id: 'ao-smith',
    name: 'AO Smith',
    fullName: 'AO Smith Water Purifiers',
    tagline: 'Innovation has a name',
    description: 'AO Smith is known for its innovative water heating and purification solutions with advanced technology. Reliable AO Smith service in Bangalore.',
    color: '#dc2626',
    services: ['AO Smith Repair', 'AO Smith Service', 'AO Smith Filter Change', 'AO Smith AMC'],
  },
  {
    id: 'lg',
    name: 'LG',
    fullName: 'LG Water Purifiers',
    tagline: 'Life\'s Good',
    description: 'LG offers cutting-edge water purification with mineral enhancement technology for healthier drinking water. Trusted LG purifier service in Bangalore.',
    color: '#b91c1c',
    services: ['LG Repair', 'LG Service', 'LG Filter Change', 'LG AMC'],
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rohit Sharma',
    location: 'Koramangala, Bangalore',
    rating: 5,
    text: 'Very quick response and service. Technician was professional and fixed the problem in 30 minutes.',
    service: 'RO Repair',
  },
  {
    id: 2,
    name: 'Sneha Verma',
    location: 'Whitefield, Bangalore',
    rating: 5,
    text: 'Great service! My RO is working like new now. Highly recommended!',
    service: 'Filter Replacement',
  },
  {
    id: 3,
    name: 'Amit Patel',
    location: 'Electronic City, Bangalore',
    rating: 5,
    text: 'Genuine spare parts and very polite staff. Fantastic experience.',
    service: 'AMC Plan',
  },
  {
    id: 4,
    name: 'Kavya N',
    location: 'JP Nagar, Bangalore',
    rating: 5,
    text: 'Affordable pricing and timely service. Really impressed!',
    service: 'Periodic Maintenance',
  },
];

export const FAQS = [
  {
    id: 1,
    question: 'How quickly can you provide service in Bangalore?',
    answer: 'We provide same-day doorstep service across Bangalore. Our technicians are available from 8 AM to 8 PM, and we aim to reach you within 1-3 hours of your call.',
  },
  {
    id: 2,
    question: 'Do you use genuine spare parts?',
    answer: 'Yes, we only use 100% genuine and original spare parts from the respective brands. We never use third-party or compatible parts.',
  },
  {
    id: 3,
    question: 'Is there any service warranty?',
    answer: 'Yes, we provide up to 90 days service warranty on all our repairs. The warranty period varies depending on the type of service and parts replaced.',
  },
  {
    id: 4,
    question: 'What are your service charges in Bangalore?',
    answer: 'Our service charges start from ₹299 for basic maintenance. The final cost depends on the type of service, parts required, and your RO brand. We provide a transparent quote before starting any work.',
  },
  {
    id: 5,
    question: 'Do you provide AMC plans?',
    answer: 'Yes, we offer comprehensive Annual Maintenance Contracts (AMC) that include regular maintenance visits, filter changes, and priority service across Bangalore.',
  },
  {
    id: 6,
    question: 'Which areas in Bangalore do you service?',
    answer: 'We service all major areas in Bangalore including Koramangala, Whitefield, Electronic City, HSR Layout, JP Nagar, Indiranagar, Bellandur, Sarjapur Road, Marathahalli, and more.',
  },
];

export const SERVICE_AREAS = [
  'Koramangala',
  'Whitefield',
  'Electronic City',
  'HSR Layout',
  'JP Nagar',
  'Indiranagar',
  'Bellandur',
  'Sarjapur Road',
  'Marathahalli',
  'BTM Layout',
  'Jayanagar',
  'Banashankari',
  'Hebbal',
  'Yelahanka',
  'Rajajinagar',
  'Basavanagudi',
  'Malleshwaram',
  'Frazer Town',
  'Domlur',
  'Murugeshpalya',
];

export const WHY_CHOOSE_US = [
  {
    title: 'Same Day Service',
    description: 'Quick response & same day service at your doorstep.',
    icon: 'Clock',
  },
  {
    title: 'Certified Technicians',
    description: 'Trained & experienced professionals.',
    icon: 'Award',
  },
  {
    title: 'Genuine Spare Parts',
    description: '100% original & branded spare parts.',
    icon: 'Shield',
  },
  {
    title: 'Affordable Pricing',
    description: 'Transparent pricing & no hidden charges.',
    icon: 'IndianRupee',
  },
  {
    title: 'Warranty on Service',
    description: 'Service warranty for your peace of mind.',
    icon: 'CheckCircle',
  },
  {
    title: '24x7 Support',
    description: 'We are available 24x7 for you.',
    icon: 'Headphones',
  },
];
